// Code generated by ./internal/inspect/provider/onnxrt/gen. DO NOT EDIT.
//
// Source: onnxruntime_c_api.h, ORT_API_VERSION 29, 414 members.

package onnxrt

// apiVersion is the OrtApi version these indices were taken from.
//
// GetApi returns NULL for a version the library does not implement, which
// is how an older runtime is refused. Indices must never be used against a
// different version: the struct is append-only, so an older one has the
// same prefix, but nothing guarantees that for a version we did not read.
const apiVersion = 29

// OrtApi member indices.
const (
	idxGetErrorMessage                  = 2
	idxCreateEnv                        = 3
	idxCreateSessionFromArray           = 8
	idxRun                              = 9
	idxCreateSessionOptions             = 10
	idxSetSessionGraphOptimizationLevel = 23
	idxSetIntraOpNumThreads             = 24
	idxSessionGetInputCount             = 30
	idxSessionGetOutputCount            = 31
	idxSessionGetInputName              = 36
	idxSessionGetOutputName             = 37
	idxCreateTensorWithDataAsOrtValue   = 49
	idxGetTensorMutableData             = 51
	idxGetDimensionsCount               = 61
	idxGetDimensions                    = 62
	idxGetTensorTypeAndShape            = 65
	idxCreateCpuMemoryInfo              = 69
	idxAllocatorFree                    = 76
	idxGetAllocatorWithDefaultOptions   = 78
	idxReleaseEnv                       = 92
	idxReleaseStatus                    = 93
	idxReleaseMemoryInfo                = 94
	idxReleaseSession                   = 95
	idxReleaseValue                     = 96
	idxReleaseTensorTypeAndShapeInfo    = 99
	idxReleaseSessionOptions            = 100
)
