// Package tokenizer implements the byte-level BPE tokenizer that
// openai/privacy-filter was trained with.
//
// It exists because the alternatives both cost more than they save: HF's Rust
// tokenizers need cgo, and a Python sidecar needs a Python runtime. Neither
// fits a daemon that is otherwise a single static Go binary.
//
// Correctness here means byte-identical to the reference implementation, not
// merely reasonable. Tokenizing differently from the training tokenizer does
// not produce an error -- it produces confident nonsense, because the model
// sees a sequence it was never trained on. testdata/fixtures.json holds token
// IDs generated by transformers.js, and the tests require an exact match.
package tokenizer

import (
	"encoding/json"
	"fmt"
	"io"
	"sort"
	"strings"
)

// Token is one piece of the input.
type Token struct {
	// ID is the vocabulary index handed to the model.
	ID int32
	// Start and End are BYTE offsets into the text that was encoded.
	//
	// They are derived rather than reported by a separate offset mechanism:
	// this tokenizer has no normalizer and the byte-level alphabet covers
	// every byte, so the tokens' decoded bytes concatenate back to the input
	// exactly. Offsets are therefore running sums, and Encode verifies the
	// reconstruction rather than assuming it.
	Start, End int
}

// Tokenizer encodes text into model token IDs.
type Tokenizer struct {
	vocab  map[string]int32
	ranks  map[string]int32 // "left\x00right" -> merge rank
	tokens map[int32]string // id -> vocabulary entry, for decoding
}

// tokenizerFile is the subset of tokenizer.json this implementation reads.
//
// The unread fields are checked rather than ignored: a normalizer, a
// truncation rule or a non-BPE model would each change the output, and
// silently skipping them would produce a tokenizer that looks fine and
// disagrees with the model.
type tokenizerFile struct {
	Normalizer   json.RawMessage `json:"normalizer"`
	Truncation   json.RawMessage `json:"truncation"`
	AddedTokens  []addedToken    `json:"added_tokens"`
	PreTokenizer json.RawMessage `json:"pre_tokenizer"`
	Model        struct {
		Type          string           `json:"type"`
		Vocab         map[string]int32 `json:"vocab"`
		Merges        [][]string       `json:"merges"`
		IgnoreMerges  bool             `json:"ignore_merges"`
		ByteFallback  bool             `json:"byte_fallback"`
		Dropout       *float64         `json:"dropout"`
		UnkToken      *string          `json:"unk_token"`
		ContinuingPfx *string          `json:"continuing_subword_prefix"`
		EndOfWordSfx  *string          `json:"end_of_word_suffix"`
	} `json:"model"`
}

type addedToken struct {
	ID      int32  `json:"id"`
	Content string `json:"content"`
	Special bool   `json:"special"`
}

// Load reads a tokenizer.json.
//
// It rejects anything it was not written for. The cost of accepting a
// tokenizer with, say, a normalizer this code ignores is not a crash; it is
// spans that point at the wrong bytes of the caller's request body.
func Load(r io.Reader) (*Tokenizer, error) {
	var f tokenizerFile
	dec := json.NewDecoder(r)
	if err := dec.Decode(&f); err != nil {
		return nil, fmt.Errorf("tokenizer: parsing tokenizer.json: %w", err)
	}

	if f.Model.Type != "BPE" {
		return nil, fmt.Errorf("tokenizer: model type %q is not supported; want BPE", f.Model.Type)
	}
	if len(f.Model.Vocab) == 0 {
		return nil, fmt.Errorf("tokenizer: empty vocabulary")
	}
	if len(f.Model.Merges) == 0 {
		return nil, fmt.Errorf("tokenizer: no merges")
	}
	if !isJSONNull(f.Normalizer) {
		return nil, fmt.Errorf("tokenizer: a normalizer is configured; this implementation assumes none, and applying one changes byte offsets")
	}
	if !isJSONNull(f.Truncation) {
		return nil, fmt.Errorf("tokenizer: truncation is configured; this implementation does not truncate")
	}
	if f.Model.Dropout != nil && *f.Model.Dropout != 0 {
		return nil, fmt.Errorf("tokenizer: BPE dropout is configured; encoding would be non-deterministic")
	}
	if nonEmpty(f.Model.ContinuingPfx) || nonEmpty(f.Model.EndOfWordSfx) {
		return nil, fmt.Errorf("tokenizer: continuing_subword_prefix / end_of_word_suffix are not supported")
	}

	t := &Tokenizer{
		vocab:  make(map[string]int32, len(f.Model.Vocab)+len(f.AddedTokens)),
		ranks:  make(map[string]int32, len(f.Model.Merges)),
		tokens: make(map[int32]string, len(f.Model.Vocab)+len(f.AddedTokens)),
	}
	for tok, id := range f.Model.Vocab {
		t.vocab[tok] = id
		t.tokens[id] = tok
	}
	// Added tokens are the specials (<|endoftext|> and friends). They are
	// recorded so an ID can be decoded, but never produced: this tokenizer
	// encodes content, and a special token appearing because the content
	// spelled it out is prompt injection with extra steps.
	for _, at := range f.AddedTokens {
		t.tokens[at.ID] = at.Content
	}

	for i, m := range f.Model.Merges {
		if len(m) != 2 {
			return nil, fmt.Errorf("tokenizer: merge %d has %d parts, want 2", i, len(m))
		}
		t.ranks[m[0]+"\x00"+m[1]] = int32(i)
	}
	return t, nil
}

func isJSONNull(raw json.RawMessage) bool {
	s := strings.TrimSpace(string(raw))
	return s == "" || s == "null"
}

func nonEmpty(p *string) bool { return p != nil && *p != "" }

// VocabSize reports how many entries the vocabulary holds.
func (t *Tokenizer) VocabSize() int { return len(t.vocab) }

// Encode tokenizes text.
//
// The returned tokens tile the input exactly: token i ends where token i+1
// begins, the first starts at 0 and the last ends at len(text). Encode
// verifies that before returning, because every downstream use of these
// offsets -- redaction above all -- assumes it, and a silent gap would move
// every subsequent span.
func (t *Tokenizer) Encode(text string) ([]Token, error) {
	if text == "" {
		return nil, nil
	}

	var out []Token
	var encErr error

	preTokenize(text, func(start, end int) {
		if encErr != nil {
			return
		}
		piece := text[start:end]
		ids, err := t.encodePiece(piece)
		if err != nil {
			encErr = fmt.Errorf("at byte %d: %w", start, err)
			return
		}

		at := start
		for _, id := range ids {
			raw, ok := decodeToken(t.tokens[id])
			if !ok {
				encErr = fmt.Errorf("token %d (%q) is not byte-level", id, t.tokens[id])
				return
			}
			out = append(out, Token{ID: id, Start: at, End: at + len(raw)})
			at += len(raw)
		}
		if at != end {
			encErr = fmt.Errorf("piece %q at byte %d re-encoded to %d bytes", piece, start, at-start)
		}
	})
	if encErr != nil {
		return nil, fmt.Errorf("tokenizer: %w", encErr)
	}

	if err := verifyTiling(text, out); err != nil {
		return nil, fmt.Errorf("tokenizer: %w", err)
	}
	return out, nil
}

// verifyTiling checks the offsets cover the input with no gap or overlap.
func verifyTiling(text string, toks []Token) error {
	at := 0
	for i, tk := range toks {
		if tk.Start != at {
			return fmt.Errorf("token %d starts at %d, expected %d", i, tk.Start, at)
		}
		if tk.End < tk.Start {
			return fmt.Errorf("token %d is inverted: [%d,%d)", i, tk.Start, tk.End)
		}
		at = tk.End
	}
	if at != len(text) {
		return fmt.Errorf("tokens cover %d bytes of %d", at, len(text))
	}
	return nil
}

// IDs is Encode reduced to the model input.
func (t *Tokenizer) IDs(text string) ([]int32, error) {
	toks, err := t.Encode(text)
	if err != nil {
		return nil, err
	}
	ids := make([]int32, len(toks))
	for i, tk := range toks {
		ids[i] = tk.ID
	}
	return ids, nil
}

// Decode maps IDs back to text. It is used by the tests to prove encoding is
// lossless, which is what makes the derived byte offsets sound.
func (t *Tokenizer) Decode(ids []int32) (string, error) {
	var b strings.Builder
	for _, id := range ids {
		tok, ok := t.tokens[id]
		if !ok {
			return "", fmt.Errorf("tokenizer: unknown token id %d", id)
		}
		raw, ok := decodeToken(tok)
		if !ok {
			return "", fmt.Errorf("tokenizer: token %d (%q) is not byte-level", id, tok)
		}
		b.Write(raw)
	}
	return b.String(), nil
}

// encodePiece runs BPE over one pre-tokenized piece.
func (t *Tokenizer) encodePiece(piece string) ([]int32, error) {
	mapped := encodeBytes(piece)

	// A piece present in the vocabulary verbatim is used as-is. The merge
	// loop would reach the same answer, so this is only a shortcut -- but it
	// is the common case for short words and it avoids the allocation.
	if id, ok := t.vocab[mapped]; ok {
		return []int32{id}, nil
	}

	parts := splitRunes(mapped)
	parts = t.merge(parts)

	ids := make([]int32, 0, len(parts))
	for _, p := range parts {
		id, ok := t.vocab[p]
		if !ok {
			// Every single byte of the alphabet is in the vocabulary, so an
			// unmergeable piece still resolves. Reaching here means the
			// vocabulary is incomplete, and emitting an unknown token would
			// desynchronise the offsets from the text.
			return nil, fmt.Errorf("no vocabulary entry for %q", p)
		}
		ids = append(ids, id)
	}
	return ids, nil
}

// merge applies BPE merges by rank until none applies.
func (t *Tokenizer) merge(parts []string) []string {
	for len(parts) > 1 {
		bestRank := int32(-1)
		bestAt := -1
		for i := 0; i+1 < len(parts); i++ {
			rank, ok := t.ranks[parts[i]+"\x00"+parts[i+1]]
			if !ok {
				continue
			}
			// Lowest rank wins; on a tie the leftmost pair merges first,
			// which is what the reference implementation does.
			if bestAt < 0 || rank < bestRank {
				bestRank, bestAt = rank, i
			}
		}
		if bestAt < 0 {
			break
		}
		merged := parts[bestAt] + parts[bestAt+1]
		parts = append(parts[:bestAt], append([]string{merged}, parts[bestAt+2:]...)...)
	}
	return parts
}

// splitRunes splits a byte-level-mapped string into single runes, which are
// the atoms BPE starts from.
func splitRunes(s string) []string {
	out := make([]string, 0, len(s))
	for _, r := range s {
		out = append(out, string(r))
	}
	return out
}

// SortedSpecialIDs returns the added-token IDs, for tests and diagnostics.
func (t *Tokenizer) SortedSpecialIDs() []int32 {
	var ids []int32
	for id, tok := range t.tokens {
		if strings.HasPrefix(tok, "<|") && strings.HasSuffix(tok, "|>") {
			ids = append(ids, id)
		}
	}
	sort.Slice(ids, func(i, j int) bool { return ids[i] < ids[j] })
	return ids
}
