#!/usr/bin/env bash
# Prints the size and SHA-256 of each Privacy Filter model file at a pinned
# revision, in the form internal/inspect/provider/privacyfilter/models.go wants.
#
# The digests in models.go are the control that makes the download source
# irrelevant, so they must never be typed by hand or copied from a listing.
# Run this, paste the output, and the bytes either match at download time or
# they are refused.
#
#   scripts/model-digests.sh [revision]
#
# Downloads about 950MB to a temporary directory and deletes it afterwards.
set -euo pipefail

REPO="openai/privacy-filter"
REV="${1:-7ffa9a043d54d1be65afb281eddf0ffbe629385b}"

FILES=(
  "tokenizer.json"
  "config.json"
  "viterbi_calibration.json"
  "onnx/model_q4.onnx"
  "onnx/model_q4.onnx_data"
)

if [[ ! "$REV" =~ ^[0-9a-f]{40}$ ]]; then
  echo "revision must be a 40-character commit SHA, not a branch: a branch moves" >&2
  echo "under the pin and every install starts failing at once with no local change" >&2
  echo "to explain it." >&2
  exit 2
fi

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

echo "# ${REPO} @ ${REV}"
echo "# generated by scripts/model-digests.sh"
for f in "${FILES[@]}"; do
  url="https://huggingface.co/${REPO}/resolve/${REV}/${f}"
  out="$tmp/$(basename "$f")"
  echo "downloading ${f}..." >&2
  curl -fsSL -o "$out" "$url"

  size="$(wc -c < "$out" | tr -d ' ')"
  if command -v sha256sum >/dev/null 2>&1; then
    sum="$(sha256sum "$out" | cut -d' ' -f1)"
  else
    sum="$(shasum -a 256 "$out" | cut -d' ' -f1)"
  fi

  printf '{\n\tName: %q, URL: hfURL(%q),\n\tSize: %s, SHA256: %q,\n},\n' \
    "$(basename "$f")" "$f" "$size" "$sum"
done
