// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: agentmon/v1/pty.proto

package ptygrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentmonPTY_ExecPTY_FullMethodName = "/agentmon.v1.AgentmonPTY/ExecPTY"
)

// AgentmonPTYClient is the client API for AgentmonPTY service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentmonPTY provides interactive PTY execution (stdin/stdout bytes, resize, signals).
type AgentmonPTYClient interface {
	ExecPTY(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecPTYClientMsg, ExecPTYServerMsg], error)
}

type agentmonPTYClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentmonPTYClient(cc grpc.ClientConnInterface) AgentmonPTYClient {
	return &agentmonPTYClient{cc}
}

func (c *agentmonPTYClient) ExecPTY(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecPTYClientMsg, ExecPTYServerMsg], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentmonPTY_ServiceDesc.Streams[0], AgentmonPTY_ExecPTY_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecPTYClientMsg, ExecPTYServerMsg]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentmonPTY_ExecPTYClient = grpc.BidiStreamingClient[ExecPTYClientMsg, ExecPTYServerMsg]

// AgentmonPTYServer is the server API for AgentmonPTY service.
// All implementations must embed UnimplementedAgentmonPTYServer
// for forward compatibility.
//
// AgentmonPTY provides interactive PTY execution (stdin/stdout bytes, resize, signals).
type AgentmonPTYServer interface {
	ExecPTY(grpc.BidiStreamingServer[ExecPTYClientMsg, ExecPTYServerMsg]) error
	mustEmbedUnimplementedAgentmonPTYServer()
}

// UnimplementedAgentmonPTYServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentmonPTYServer struct{}

func (UnimplementedAgentmonPTYServer) ExecPTY(grpc.BidiStreamingServer[ExecPTYClientMsg, ExecPTYServerMsg]) error {
	return status.Error(codes.Unimplemented, "method ExecPTY not implemented")
}
func (UnimplementedAgentmonPTYServer) mustEmbedUnimplementedAgentmonPTYServer() {}
func (UnimplementedAgentmonPTYServer) testEmbeddedByValue()                     {}

// UnsafeAgentmonPTYServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentmonPTYServer will
// result in compilation errors.
type UnsafeAgentmonPTYServer interface {
	mustEmbedUnimplementedAgentmonPTYServer()
}

func RegisterAgentmonPTYServer(s grpc.ServiceRegistrar, srv AgentmonPTYServer) {
	// If the following call panics, it indicates UnimplementedAgentmonPTYServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentmonPTY_ServiceDesc, srv)
}

func _AgentmonPTY_ExecPTY_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentmonPTYServer).ExecPTY(&grpc.GenericServerStream[ExecPTYClientMsg, ExecPTYServerMsg]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentmonPTY_ExecPTYServer = grpc.BidiStreamingServer[ExecPTYClientMsg, ExecPTYServerMsg]

// AgentmonPTY_ServiceDesc is the grpc.ServiceDesc for AgentmonPTY service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentmonPTY_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agentmon.v1.AgentmonPTY",
	HandlerType: (*AgentmonPTYServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExecPTY",
			Handler:       _AgentmonPTY_ExecPTY_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "agentmon/v1/pty.proto",
}
